// Generated by CoffeeScript 1.6.2
(function() {
  var manager, obj, vdvc;

  vdvc = require('./vdvc');

  manager = null;

  obj = null;

  exports.groupOne = {
    setUp: function(cb) {
      manager = vdvc["new"]();
      obj = {
        name: 'derek',
        age: '20',
        speak: function() {
          return console.log("What's up");
        }
      };
      return cb();
    },
    testClone: function(test) {
      var clonedObj;

      clonedObj = manager.clone(obj);
      test.deepEqual(clonedObj, obj, "Clone failed");
      return test.done();
    },
    testAddAndCommit: function(test) {
      test.doesNotThrow(function() {
        manager.add(obj);
        return manager.commit();
      }, 'Should not throw errors');
      return test.done();
    },
    testPrev: function(test) {
      var oldName, prev_obj;

      manager.add(obj);
      manager.commit();
      oldName = obj.name;
      obj.name = 'nemo';
      manager.add(obj);
      manager.commit();
      prev_obj = manager.prev(obj);
      test.strictEqual(prev_obj.name, oldName);
      return test.done();
    }
  };

}).call(this);
