// Generated by CoffeeScript 1.6.2
(function() {
  var derek, manager, now_derek, old_derek, prev_derek, prev_manager, prev_tom, sec_manager, tom, vdvc;

  vdvc = require('./vdvc');

  manager = vdvc["new"]();

  derek = {
    name: 'derek',
    age: 13,
    move: function() {
      return console.log('haha');
    }
  };

  manager.add(derek);

  console.log(derek);

  console.log(manager.buffer);

  manager.commit();

  console.log(manager.store);

  derek.age = 16;

  derek.move = function() {
    return console.log('hehe');
  };

  derek.move();

  manager.add(derek);

  manager.commit();

  sec_manager = vdvc["new"]();

  sec_manager.add(manager);

  sec_manager.commit();

  derek.age = 20;

  manager.add(derek);

  manager.commit();

  prev_derek = manager.prev(derek);

  console.log(prev_derek.age);

  prev_derek.move();

  sec_manager.add(manager);

  sec_manager.commit();

  now_derek = manager.next(prev_derek);

  console.log(now_derek.age);

  now_derek.move();

  prev_derek = manager.prev(prev_derek);

  console.log(prev_derek.age);

  prev_derek.move();

  prev_manager = sec_manager.prev(manager);

  now_derek = prev_manager.next(prev_derek);

  console.log(now_derek.age);

  now_derek.move();

  old_derek = manager.reset(now_derek, 0);

  old_derek.move();

  console.log(old_derek.age);

  vdvc = require('./vdvc');

  manager = vdvc["new"]();

  derek = {
    name: 'Derek',
    age: '20',
    speak: function() {
      return console.log('Yo how is it going?');
    }
  };

  tom = {
    name: 'Tom',
    age: '24',
    speak: function() {
      return console.log('Not bad.');
    }
  };

  manager.add(derek, tom);

  manager.commit();

  derek.age = '40';

  tom.speak = function() {
    return console.log('Bullshit');
  };

  manager.add(derek, tom);

  manager.commit();

  prev_derek = manager.prev(derek);

  console.log(prev_derek.age);

  prev_tom = manager.prev(tom);

  prev_tom.speak();

}).call(this);
